package solution_diskonHarga.sandbox;

/*Generated by MPS */


public class SetraJayaAbadi {
  public static void main(String[] args) {
    System.out.println("Nama Market : " + "SetraJayaAbadi");
    System.out.println("List Produk : ");
    System.out.println();
    {
      System.out.println("Produk : " + "Minyak");
      int total = 19000;
      System.out.println(" Harga Akhir : " + total);
    }
    {
      System.out.println("Produk : " + "Beras");
      int total = 13500;
      System.out.println(" Harga Akhir : " + total);
    }
    {
      System.out.println("Produk : " + "Air Mineral");
      int total = 45000;
      System.out.println(" Harga Akhir : " + total);
    }
  }
}
