package DiskonHarga.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class Diskon_Constraints extends BaseConstraintsDescriptor {
  /*package*/ Diskon_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.Diskon$ML, initContext);
    record(new Angka_PD(this));
  }

  /*package*/ static final class Angka_PD extends BasePropertyConstraintsDescriptor {
    public Angka_PD(ConstraintsDescriptor container) {
      super(PROPS.angka$VA47, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:3942e82d-f6c7-42a7-a6a3-0ef163d943ed(DiskonHarga.constraints)", "7366529339877788077"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue <= 100 && propertyValue > 0;
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Diskon$ML = MetaAdapterFactory.getConcept(0x72952a5e6c024ddbL, 0x862b2e9250db5990L, 0x35d3555a0a40efe9L, "DiskonHarga.structure.Diskon");
  }

  private static final class PROPS {
    /*package*/ static final SProperty angka$VA47 = MetaAdapterFactory.getProperty(0x72952a5e6c024ddbL, 0x862b2e9250db5990L, 0x35d3555a0a40efe9L, 0x35d3555a0a40efeaL, "angka");
  }
}
