package DiskonHarga.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Diskon_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Harga_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Main_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Market_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Produk_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x72952a5e6c024ddbL, 0x862b2e9250db5990L, 0x35d3555a0a40efe9L), MetaIdFactory.conceptId(0x72952a5e6c024ddbL, 0x862b2e9250db5990L, 0x35d3555a0a40efe8L), MetaIdFactory.conceptId(0x72952a5e6c024ddbL, 0x862b2e9250db5990L, 0x51a1601f8614f5eaL), MetaIdFactory.conceptId(0x72952a5e6c024ddbL, 0x862b2e9250db5990L, 0x35d3555a0a40efe1L), MetaIdFactory.conceptId(0x72952a5e6c024ddbL, 0x862b2e9250db5990L, 0x35d3555a0a40efe3L)).seal();
}
