package DiskonHarga.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SProperty;

public final class Produk__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x72952a5e6c024ddbL, 0x862b2e9250db5990L, 0x35d3555a0a40efe3L, "DiskonHarga.structure.Produk");

  public static final SMethod<Integer> getTruePrice_id4fJBWw6gVZd = new SMethodBuilder<Integer>(new SJavaCompoundTypeImpl(Integer.TYPE)).name("getTruePrice").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4895307001422397389L).languageId(0x862b2e9250db5990L, 0x72952a5e6c024ddbL).build2();
  public static final SMethod<Integer> getDsc_id24oSWWZ0XDp = new SMethodBuilder<Integer>(new SJavaCompoundTypeImpl(Integer.TYPE)).name("getDsc").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(2384906481947630169L).languageId(0x862b2e9250db5990L, 0x72952a5e6c024ddbL).build2();
  public static final SMethod<Integer> getPrc_id24oSWWZ0Zji = new SMethodBuilder<Integer>(new SJavaCompoundTypeImpl(Integer.TYPE)).name("getPrc").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(2384906481947636946L).languageId(0x862b2e9250db5990L, 0x72952a5e6c024ddbL).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(getTruePrice_id4fJBWw6gVZd, getDsc_id24oSWWZ0XDp, getPrc_id24oSWWZ0Zji);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static int getTruePrice_id4fJBWw6gVZd(@NotNull SNode __thisNode__) {
    return ((int) Produk__BehaviorDescriptor.getPrc_id24oSWWZ0Zji.invoke(__thisNode__)) - (((int) Produk__BehaviorDescriptor.getPrc_id24oSWWZ0Zji.invoke(__thisNode__)) * ((int) Produk__BehaviorDescriptor.getDsc_id24oSWWZ0XDp.invoke(__thisNode__)) / 100);
  }
  /*package*/ static int getDsc_id24oSWWZ0XDp(@NotNull SNode __thisNode__) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(__thisNode__, LINKS.discount$9FA3), PROPS.angka$VA47);
  }
  /*package*/ static int getPrc_id24oSWWZ0Zji(@NotNull SNode __thisNode__) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(__thisNode__, LINKS.price$6fKq), PROPS.price$VAiD);
  }

  /*package*/ Produk__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((Integer) getTruePrice_id4fJBWw6gVZd(node));
      case 1:
        return (T) ((Integer) getDsc_id24oSWWZ0XDp(node));
      case 2:
        return (T) ((Integer) getPrc_id24oSWWZ0Zji(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink discount$9FA3 = MetaAdapterFactory.getContainmentLink(0x72952a5e6c024ddbL, 0x862b2e9250db5990L, 0x35d3555a0a40efe3L, 0x35d3555a0a41b223L, "discount");
    /*package*/ static final SContainmentLink price$6fKq = MetaAdapterFactory.getContainmentLink(0x72952a5e6c024ddbL, 0x862b2e9250db5990L, 0x35d3555a0a40efe3L, 0x35d3555a0a41b1c2L, "price");
  }

  private static final class PROPS {
    /*package*/ static final SProperty angka$VA47 = MetaAdapterFactory.getProperty(0x72952a5e6c024ddbL, 0x862b2e9250db5990L, 0x35d3555a0a40efe9L, 0x35d3555a0a40efeaL, "angka");
    /*package*/ static final SProperty price$VAiD = MetaAdapterFactory.getProperty(0x72952a5e6c024ddbL, 0x862b2e9250db5990L, 0x35d3555a0a40efe8L, 0x35d3555a0a40efebL, "price");
  }
}
