package DiskonHarga.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Diskon = 0;
  public static final int Harga = 1;
  public static final int Main = 2;
  public static final int Market = 3;
  public static final int Produk = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x72952a5e6c024ddbL, 0x862b2e9250db5990L);
    builder.put(0x35d3555a0a40efe9L, Diskon);
    builder.put(0x35d3555a0a40efe8L, Harga);
    builder.put(0x51a1601f8614f5eaL, Main);
    builder.put(0x35d3555a0a40efe1L, Market);
    builder.put(0x35d3555a0a40efe3L, Produk);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
